server:
  port: 8081

spring:
  application:
    name: spring-ms-one

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#ssh-keygen -t rsa -b 4096 -C "jayesh.patil1594@gmail.com"